### PR TITLE
Update to version 0.9.0

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #6

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @awvwgk! I suggest we wait with merging this until v0.9.1 is out, so we can merge that straight after. 0.9.0 fixes a whole bunch of things, but has one unfortunate regression on macOS 10.X so it'd be nice to merge the two releases at the same time.

**Comment by awvwgk** [comment]
Alright, then let's not package 0.9.0 for conda-forge

**Comment by awvwgk** [comment]
Is this a known failure?

```
_____________________________ test_executable_bit ______________________________

sdist_executable_bit = PosixPath('/tmp/pytest-of-conda/pytest-0/test0/mesonpy-test-e_t6fig5/executable_bit-1.0.0.tar.gz')

    @pytest.mark.skipif(os.name == 'nt', reason='Executable bit does not exist on Windows')
    def test_executable_bit(sdist_executable_bit):
        sdist = tarfile.open(sdist_executable_bit, 'r:gz')
    
>       assert set((tar.name, tar.mode) for tar in sdist.getmembers()) == {
            ('executable_bit-1.0.0/PKG-INFO', 420),
            # We match the executable bit on everything
            # but PKG-INFO(we create this ourselves)
            # Note: File perms are in octal, but Python returns it in int
            ('executable_bit-1.0.0/example-script.py', int('755', 8)),
            ('executable_bit-1.0.0/example.c', int('644', 8)),
            ('executable_bit-1.0.0/executable_module.py', int('755', 8)),
            ('executable_bit-1.0.0/meson.build', int('644', 8)),
            ('executable_bit-1.0.0/pyproject.toml', int('644', 8)),
        }
E       AssertionError: assert {('executable_bit-1.0.0/PKG-INFO', 420),\n ('executable_bit-1.0.0/example-script.py', 509),\n ('executable_bit-1.0.0/example.c', 436),\n ('executable_bit-1.0.0/executable_module.py', 509),\n ('executable_bit-1.0.0/meson.build', 436),\n ('executable_bit-1.0.0/pyproject.toml', 436)} == {('executable_bit-1.0.0/PKG-INFO', 420),\n ('executable_bit-1.0.0/example-script.py', 493),\n ('executable_bit-1.0.0/example.c', 420),\n ('executable_bit-1.0.0/executable_module.py', 493),\n ('executable_bit-1.0.0/meson.build', 420),\n ('executable_bit-1.0.0/pyproject.toml', 420)}
E         Extra items in the left set:
E         ('executable_bit-1.0.0/pyproject.toml', 436)
E         ('executable_bit-1.0.0/example.c', 436)
E         ('executable_bit-1.0.0/executable_module.py', 509)
E         ('executable_bit-1.0.0/example-script.py', 509)
E         ('executable_bit-1.0.0/meson.build', 436)
E         Extra items in the right set:
E         ('executable_bit-1.0.0/example-script.py', 493)
E         ('executable_bit-1.0.0/example.c', 420)
E         ('executable_bit-1.0.0/executable_module.py', 493)
E         ('executable_bit-1.0.0/meson.build', 420)
E         ('executable_bit-1.0.0/pyproject.toml', 420)
E         Full diff:
E           {
E            ('executable_bit-1.0.0/PKG-INFO', 420),
E         -  ('executable_bit-1.0.0/example-script.py', 493),
E         ?                                             ^ -
E         +  ('executable_bit-1.0.0/example-script.py', 509),
E         ?                                             ^^
E         -  ('executable_bit-1.0.0/example.c', 420),
E         ?                                      ^^
E         +  ('executable_bit-1.0.0/example.c', 436),
E         ?                                      ^^
E         -  ('executable_bit-1.0.0/executable_module.py', 493),
E         ?                                                ^ -
E         +  ('executable_bit-1.0.0/executable_module.py', 509),
E         ?                                                ^^
E         -  ('executable_bit-1.0.0/meson.build', 420),
E         ?                                        ^^
E         +  ('executable_bit-1.0.0/meson.build', 436),
E         ?                                        ^^
E         -  ('executable_bit-1.0.0/pyproject.toml', 420),
E         ?                                           ^^
E         +  ('executable_bit-1.0.0/pyproject.toml', 436),
E         ?                                           ^^
E           }

tests/test_sdist.py:77: AssertionError
---------------------------- Captured stdout setup -----------------------------
! Using Meson to generate the project metadata (no `project` section in pyproject.toml)
+ meson setup --native-file=$SRC_DIR/tests/packages/executable-bit/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2 --prefix=$PREFIX $SRC_DIR/tests/packages/executable-bit $SRC_DIR/tests/packages/executable-bit/.mesonpy-vvtcczsb/build
The Meson build system
Version: 0.63.2
Source dir: $SRC_DIR/tests/packages/executable-bit
Build dir: $SRC_DIR/tests/packages/executable-bit/.mesonpy-vvtcczsb/build
Build type: native build
Project name: executable-bit
Project version: 1.0.0
C compiler for the host machine: $PREFIX/bin/x86_64-conda-linux-gnu-cc (gcc 10.4.0 "x86_64-conda-linux-gnu-cc (conda-forge gcc 10.4.0-16) 10.4.0")
C linker for the host machine: $PREFIX/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.36.1
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python found: YES ($PREFIX/bin/python)
Build targets in project: 1

executable-bit 1.0.0

  User defined options
    Native files: $SRC_DIR/tests/packages/executable-bit/.mesonpy-native-file.ini
    debug       : false
    optimization: 2
    prefix      : $PREFIX

Found ninja-1.11.0 at $PREFIX/bin/ninja
+ meson dist --allow-dirty --no-tests --formats gztar
Created $SRC_DIR/tests/packages/executable-bit/.mesonpy-vvtcczsb/build/meson-dist/executable-bit-1.0.0.tar.gz
=========================== short test summary info ============================
FAILED tests/test_sdist.py::test_executable_bit - AssertionError: assert {('e...
=================== 1 failed, 50 passed, 2 xpassed in 37.37s ===================
```

**Comment by rgommers** [comment]
Ugh, this test is very fragile. It works in meson-python's CI now though, and it works for me locally too. It's probably because of Docker: https://blog.gougousis.net/file-permissions-the-painful-side-of-docker/. 

We can safely skip the test here. We should tweak it upstream yet again though, because it looks like it is doing too much.

The differences here are:
```python
>>> int('644', 8)
420
>>> int('664', 8)
436
```
Meaning that the test expects `-rw-r--r--` and with Docker it sees `-rw-rw-r--`. Similar for the file with the executable bit actually set:
```python
>>> int('755', 8)
493
>>> int('775', 8)
509
```
Which translates to the test wanting `-rwxr-xr-x` and it seeing `-rwxrwxr-x`.

**Comment by rgommers** [comment]
Ah nice, that fix worked plus the other failure of the `scipy-like` test is very welcome - that means meson 0.63.3 (released yesterday) contains the fix for `install_subdir` we need. Let me open a couple of PRs on the `meson-python` repo for these things.

**Comment by rgommers** [comment]
With this fix the test suite should pass: https://github.com/FFY00/meson-python/pull/165

**Review by rgommers — APPROVED** [review]
All green, in it goes. Thanks @awvwgk

**Pull request merged**
