### PR TITLE
bump to 0.6.0

### PR DESCRIPTION
**Pull request by h-vetinari**
Not sure why the bot hasn't come through yet. However, since the patch will need a rebase, this will need human interaction in any case, so I thought I'd get started. In the context of this, wanted to see if we can use github sources directly.

Bump to 0.6.0 comes after, though that is still blocked on https://github.com/conda-forge/staged-recipes/pull/19352

### CODE REVIEW

**Comment by rgommers** [comment]
Thanks @h-vetinari! Note that the license info has to be updated, it's MIT now.

**Comment by h-vetinari** [comment]
Not a WIP anymore, but still needs https://github.com/conda-forge/staged-recipes/pull/19352

**Review by rgommers — APPROVED** [review]
LGTM, seems ready to merge once `pyproject-metadata` is available

**Comment by h-vetinari** [comment]
Feedstock is [live](https://github.com/conda-forge/pyproject-metadata-feedstock), this can be restarted in about 2h.

**Pull request merged**
